-- Схема таблицы гостей для Supabase.
-- Выполни один раз в Supabase → SQL Editor → New query → Run.
-- Сервер обращается к таблице через секретный ключ service_role, поэтому
-- RLS можно держать включённым без политик: публичный доступ закрыт,
-- а серверу (service_role) RLS не мешает.

create table if not exists public.guests (
  id          bigint generated by default as identity primary key,
  full_name   text not null,
  phone       text not null,
  created_at  timestamptz not null default now()
);

alter table public.guests enable row level security;
